### ISSUE TITLE
Running `init` in a subdirectory of an existing repository alters the parent `config.yaml`

### ISSUE THREAD

**Issue by kzscisoft** [FAIRDataPipeline/FAIR-CLI#3]
Bug where if the user creates a new directory in an existing FAIR repository and runs `fair init` in this location, the parent repository `config.yaml` file is updated not the daughter, i.e.
```
my_project/config.yaml
```
updated as opposed to:
```
my_project/subfolder/config.yaml
```
It is unlikely the user will ever need to "sub-init" and in fact perhaps the solution is instead to disallow this possibility.

**Comment by richardreeve** [comment]
So @DennisReddyhoff... if I run `fair create new.yaml` in a subfolder, it walks up the filesystem correctly and creates a `config.yaml` stub from the higher level `.fair` folder. However, if I run `fair init` in the subfolder, it just tries to create a new `.fair` folder.

I think what it should do if walk up through the folder structure like `fair create` and say "I've found a fair repository *up here*, do you want to 1. use that or 2. create a new one here?` and abort if they choose 1. It's not very important though, so if it's super-easy I'd do it, otherwise I'd just leave it for now.
